name: Build chiaki-ng Windows arm64 (VC)

on:
  workflow_dispatch:

jobs:
  build-win_arm64:
    name: Build chiaki-ng win_arm64 (VC)
    runs-on: windows-11-arm
    env:
      CC: clang-cl.exe
      CXX: clang-cl.exe
      VULKAN_SDK: C:\VulkanSDK\
      triplet: arm64-windows
      vcpkg_baseline: 42bb0d9e8d4cf33485afb9ee2229150f79f61a1f
      VCPKG_INSTALLED_DIR: ./vcpkg_installed/
      dep_folder: deps
      libplacebo_tag: 1f1ba06aa2a83a2c75ade4150b7c0bba10531088
      QT_VERSION: "6.9.*"

    defaults:
      run:
        shell: powershell

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Clang
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true
          cmake: true
          ninja: true

      - name: Add llvm binary dir to path
        run: |
            echo "${env:LLVM_PATH}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ env.vcpkg_baseline }}
          runVcpkgInstall: false
          vcpkgJsonGlob: "vcpkg.json"

      - name: Setup Vulkan
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/warm/InstallVulkanARM64-$ver.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root ${{ env.VULKAN_SDK }}  --accept-licenses --default-answer --confirm-command install

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "arm64"

      - name: Install pip dependencies
        run: |
          ${{ env.pythonLocation }}\python.exe -m pip install --upgrade pip
          ${{ env.pythonLocation }}\python.exe -m pip install --upgrade setuptools wheel
          ${{ env.pythonLocation }}\python.exe -m pip install --upgrade scons protobuf grpcio-tools pyinstaller
          ${{ env.pythonLocation }}\python.exe -m pip install --upgrade meson
          ${{ env.pythonLocation }}\python.exe -m pip install git+https://github.com/streetpea/aqtinstall.git@master
          ${{ env.pythonLocation }}\python.exe -c 'import google.protobuf; print(google.protobuf.__file__)'

      - name: Setup Qt
        run: |
            python3 -m aqt install-qt windows desktop "${env:QT_VERSION}" win64_msvc2022_arm64_cross_compiled --autodesktop --outputdir "${{ github.workspace }}\Qt" -m qtpositioning qtwebchannel qtwebsockets qtserialport
            echo "${{ github.workspace }}\Qt\${env:QT_VERSION}\win64_msvc2022_arm64_cross_compiled\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            echo "QT_ROOT_DIR=${{ github.workspace }}\Qt\${env:QT_VERSION}\win64_msvc2022_arm64_cross_compiled\" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "QT_PLUGIN_PATH=${{ github.workspace }}\Qt\${env:QT_VERSION}\win64_msvc2022_arm64_cross_compiled\plugins" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "QML2_IMPORT_PATH=${{ github.workspace }}\Qt\${env:QT_VERSION}\win64_msvc2022_arm64_cross_compiled\qml" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
  
      - name: Setup ffmpeg
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/streetpea/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-winarm64-gpl-shared-7.1.zip" -OutFile ".\ffmpeg-n7.1-latest-winarm64-gpl-shared-7.1.zip"
          Expand-Archive -LiteralPath "ffmpeg-n7.1-latest-winarm64-gpl-shared-7.1.zip" -DestinationPath "."
          Rename-Item "ffmpeg-n7.1-latest-winarm64-gpl-shared-7.1.zip" "${{ env.dep_folder }}"

      - name: Build SPIRV-Cross
        run: |
          git clone https://github.com/KhronosGroup/SPIRV-Cross.git
          cd SPIRV-Cross
          cmake `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}\${{ env.dep_folder }}" `
          -DSPIRV_CROSS_SHARED=ON `
          -S . `
          -B build `
          -G Ninja
          cmake --build build --config Release
          cmake --install build

      - name: Setup shaderc
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $url = ((Invoke-WebRequest -UseBasicParsing -Uri "https://storage.googleapis.com/shaderc/badges/build_link_windows_vs2019_release.html").Content | Select-String -Pattern 'url=(.*)"').Matches.Groups[1].Value
          Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile .\shaderc.zip
          Expand-Archive -LiteralPath "shaderc.zip" -DestinationPath "."
          cp "./install/*" "./${{ env.dep_folder }}" -Force -Recurse
          rm "./install" -r -force

      - name: Build libplacebo
        run: |
          git clone --recursive https://github.com/haasn/libplacebo.git
          cd libplacebo
          git checkout --recurse-submodules ${{ env.libplacebo_tag }}
          git apply --ignore-whitespace --verbose ../scripts/flatpak/0002-Vulkan-use-16bit-for-p010.patch
          meson setup `
          --prefix "${{ github.workspace }}\${{ env.dep_folder }}" `
          --native-file ../meson.ini `
          "--pkg-config-path=['${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\lib\pkgconfig','${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\share\pkgconfig','${{ github.workspace }}\${{ env.dep_folder }}\lib\pkgconfig']" `
          "--cmake-prefix-path=['${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}', '${{ env.VULKAN_SDK }}', '${{ github.workspace }}\${{ env.dep_folder }}']" `
          -Dc_args="/I ${{ env.VULKAN_SDK }}Include" `
          -Dcpp_args="/I ${{ env.VULKAN_SDK }}Include" `
          -Dc_link_args="/LIBPATH:${{ env.VULKAN_SDK }}Lib" `
          -Dcpp_link_args="/LIBPATH:${{ env.VULKAN_SDK }}Lib" `
          -Ddemos=false `
          ./build
          ninja -C./build
          ninja -C./build install

      - name: Apply Patches
        run: |
          git apply --ignore-whitespace --verbose --directory=third-party/gf-complete/ scripts/windows-vc/gf-complete.patch
          git apply --ignore-whitespace --verbose scripts/windows-vc/libplacebo-pc.patch

      - name: Configure chiaki-ng
        run: |
          cmake `
          -S . `
          -B build `
          -G Ninja `
          -DCMAKE_TOOLCHAIN_FILE:STRING="vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
          -DCMAKE_BUILD_TYPE=Release `
          -DCHIAKI_ENABLE_CLI=OFF `
          -DCHIAKI_GUI_ENABLE_SDL_GAMECONTROLLER=ON `
          -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF `
          -DPYTHON_EXECUTABLE="${{ env.pythonLocation }}\python.exe" `
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}\${{ env.dep_folder }};${{ env.VULKAN_SDK }}"

      - name: Build chiaki-ng
        run: |
          cmake --build build --config Release --clean-first --target chiaki

      - name: Prepare Qt deployment package
        run: |
          mkdir chiaki-ng-Win
          cp build\gui\chiaki.exe chiaki-ng-Win
          cp build\third-party\cpp-steam-tools\cpp-steam-tools.dll chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\libcrypto-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\libssl-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\SDL2.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\hidapi.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\fftw3.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\opus.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\libspeexdsp.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\lcms2.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\miniupnpc.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\vcpkg_installed\${{ env.triplet }}\bin\json-c.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\swresample-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\avcodec-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\avutil-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\avformat-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\libplacebo-*.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\shaderc_shared.dll" chiaki-ng-Win
          cp "${{ github.workspace }}\${{ env.dep_folder }}\bin\spirv-cross-c-shared.dll" chiaki-ng-Win
          windeployqt.exe --no-translations --qmldir=gui\src\qml --release chiaki-ng-Win\chiaki.exe

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: "scripts/chiaki-ng.iss"
          options: /O+

      - name: Upload chiaki-ng Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chiaki-ng-win_arm64-VC-installer.zip
          path: chiaki-ng-windows-installer.exe
          if-no-files-found: error
          retention-days: 7
